Repository MewsSystems/fiscalization-spain, pull requests merged in 2021-01, with the labels that each got.

#14 Automated assignment of tech.be and tech.review.qa projects
  .github/workflows/pr-automation-tech-be-assign.yml
  .github/workflows/pr-automation-tech-review-qa-assign.yml
  .github/workflows/pr-automation-tech-review-qa-move-on-close.yml
Labels: dev-tested, finance

#15 Fixed publish
  .github/workflows/publish.yml
Labels: finance

#16 Updated Core lib NuGet
  src/Mews.Fiscalization.Spain/Mews.Fiscalization.Spain.csproj
Labels: easyfix, finance

#17 Changed nif info entry to accept typed tax identifier
  src/Mews.Fiscalization.Spain.Tests/Basics.cs
  src/Mews.Fiscalization.Spain/Nif/Model.cs
  src/Mews.Fiscalization.Spain/Nif/NifValidator.cs
Labels: easyfix, finance

#18 Introduced FoundButNifModifiedByServer type.
  src/Mews.Fiscalization.Spain.Tests/Basics.cs
  src/Mews.Fiscalization.Spain/Nif/Model.cs
  src/Mews.Fiscalization.Spain/Nif/NifValidator.cs
Labels: easyfix, finance

#19 Improved NIF lookup response.
  src/Mews.Fiscalization.Spain.Tests/Basics.cs
  src/Mews.Fiscalization.Spain/Nif/Model.cs
  src/Mews.Fiscalization.Spain/Nif/NifValidator.cs
Labels: easyfix, finance

#20 Fixed an issue when sending an empty request.
  src/Mews.Fiscalization.Spain.Tests/Basics.cs
  src/Mews.Fiscalization.Spain/Nif/Model.cs
Labels: easyfix, finance
